global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'revenue-analyzer'
    scrape_interval: 5s
    metrics_path: '/revenue-analyzer/actuator/prometheus'
    http_headers:
      X-username:
        values: [ "304671212" ]
      X-secret-token:
        values: [ "secret-token" ]
    static_configs:
      - targets: ['host.docker.internal:8080']