global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'revenue-analyzer'
    metrics_path: '/revenue-analyzer/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']